<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB1yzlyk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB1yzlyk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerB1yzlyk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerB1yzlyk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerB1yzlyk\appProdProjectContainer([
    'container.build_hash' => 'B1yzlyk',
    'container.build_id' => '21ddaa84',
    'container.build_time' => 1713301016,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB1yzlyk');
