<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGzksbpq\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGzksbpq/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGzksbpq.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGzksbpq\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGzksbpq\appProdProjectContainer([
    'container.build_hash' => 'Gzksbpq',
    'container.build_id' => '77ad3940',
    'container.build_time' => 1713281134,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGzksbpq');
